# [Tutorials ในส่วนของ point cloud](https://www.open3d.org/docs/release/tutorial/geometry/pointcloud.html)

In [2]:
import open3d as o3d
print(o3d.__version__)
import numpy as np

0.18.0


In [9]:
!tree . 

.
├── Dataset
│   ├── iphone7.ply
│   └── kota_circuit2.ply
├── README.md
└── clip2.ipynb

2 directories, 4 files


# What is a PLY file? 

PLY, Polygon File Format, represents 3D file format that stores graphical objects described as a collection of polygons. The purpose of this file format was to establish a simple and easy file type that is general enough to be useful for a wide range of models. PLY file format comes as ASCII as well as Binary format for compact storage and for rapid saving and loading. The file format is used by different applications that provide support for 3D files reading.

[Reference](https://docs.fileformat.com/3d/ply/)

In [3]:
path_iphone7_ply = "Dataset/iphone7.ply"
path_kota_circuit2_ply = "Dataset/kota_circuit2.ply"

# Load a ply point cloud

In [4]:
print("Load a ply point cloud, print it, and render it")
# ply_point_cloud = o3d.data.PLYPointCloud()
# pcd = o3d.io.read_point_cloud(ply_point_cloud.path)
pcd_iphone7 = o3d.io.read_point_cloud(path_iphone7_ply)
pcd_kota_circuit2 = o3d.io.read_point_cloud(path_kota_circuit2_ply)
print("iphone7:\n",pcd_iphone7)
print("kota_circuit2:\n",pcd_kota_circuit2)

Load a ply point cloud, print it, and render it
iphone7:
 PointCloud with 8076963 points.
kota_circuit2:
 PointCloud with 14640197 points.


In [12]:
points_iphone7 = np.asarray(pcd_iphone7.points)
points_kota_circuit2 = np.asarray(pcd_kota_circuit2.points)
print("iphone7:\n",points_iphone7)
print("kota_circuit2:\n",points_kota_circuit2)

iphone7:
 [[-1033.32434082  1316.9284668  -1062.46020508]
 [-1022.46795654  1315.88684082 -1062.16821289]
 [-1011.65161133  1314.84265137 -1061.86083984]
 ...
 [15163.73046875  4870.33691406  -860.22692871]
 [15154.33007812  4861.89550781  -859.56201172]
 [15145.42675781  4854.18017578  -859.59936523]]
kota_circuit2:
 [[  82.07930756 -147.18885803  -78.15903473]
 [  97.60070801  149.98822021  -53.49351883]
 [  70.49710846 -229.24028015  -78.54177856]
 ...
 [  26.64775658  -36.49408722  -89.59648132]
 [ -88.472229     49.91682816  -75.39753723]
 [ -23.17474937  335.25888062 -102.58750916]]


# Visualize point cloud

In [6]:
# o3d.visualization.draw_geometries([pcd_iphone7],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024])

In [7]:
# o3d.visualization.draw_geometries([pcd_kota_circuit2],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024])

# Voxel downsampling

Voxel downsampling uses a regular voxel grid to create a uniformly downsampled point cloud from an input point cloud. It is often used as a pre-processing step for many point cloud processing tasks. The algorithm operates in two steps:

1. Points are bucketed into voxels.
2. Each occupied voxel generates exactly one point by averaging all points inside.

In [5]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd_iphone7 = pcd_iphone7.voxel_down_sample(voxel_size=0.05)

Downsample the point cloud with a voxel of 0.05


In [6]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd_kota_circuit2 = pcd_kota_circuit2.voxel_down_sample(voxel_size=0.05)

Downsample the point cloud with a voxel of 0.05


In [8]:
# import pandas as pd
import polars as pl

In [9]:
def pcd_only_number(pcd):
    return int(str(pcd).split()[2])

In [10]:
data = {
    "" : ["pcd", "downpcd", "diff"],
    "iphone7" : [pcd_only_number(pcd_iphone7), pcd_only_number(downpcd_iphone7), (pcd_only_number(pcd_iphone7)-pcd_only_number(downpcd_iphone7))],
    "kota" : [pcd_only_number(pcd_kota_circuit2), pcd_only_number(downpcd_kota_circuit2), (pcd_only_number(pcd_kota_circuit2)-pcd_only_number(downpcd_kota_circuit2))],
}

# Creating a DataFrame
df = pl.DataFrame(data)

# Print the DataFrame
print(df)

print(28/8076963)
print(393410/14640197)

shape: (3, 3)
┌─────────┬─────────┬──────────┐
│         ┆ iphone7 ┆ kota     │
│ ---     ┆ ---     ┆ ---      │
│ str     ┆ i64     ┆ i64      │
╞═════════╪═════════╪══════════╡
│ pcd     ┆ 8076963 ┆ 14640197 │
│ downpcd ┆ 8076935 ┆ 14246787 │
│ diff    ┆ 28      ┆ 393410   │
└─────────┴─────────┴──────────┘
3.466649531513268e-06
0.026871906163557772


# Visualize downsampling

In [1]:
# o3d.visualization.draw_geometries([downpcd_iphone7],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024])

In [14]:
# o3d.visualization.draw_geometries([downpcd_kota_circuit2],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024])

# Vertex normal estimation

Another basic operation for point cloud is point normal estimation. Press N to see point normals. The keys - and + can be used to control the length of the normal.

In [21]:
print("Recompute the normal of the downsampled point cloud")
downpcd_iphone7.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

Recompute the normal of the downsampled point cloud


In [6]:
print("Recompute the normal of the downsampled point cloud")
downpcd_kota_circuit2.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))

Recompute the normal of the downsampled point cloud


# Visualize normal estimation

In [17]:
# o3d.visualization.draw_geometries([downpcd_iphone7],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024],
#                                   point_show_normal=True)

In [ ]:
o3d.visualization.draw_geometries([downpcd_kota_circuit2],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024],
                                  point_show_normal=True)

# Access estimated vertex normal

Estimated normal vectors can be retrieved from the normals variable of downpcd.

In [23]:
print("Print a normal vector of the 0th point")
print(downpcd_iphone7.normals[0])
print("Print a normal vector of the 0th point")
print(downpcd_kota_circuit2.normals[0])

Print a normal vector of the 0th point
[0. 0. 1.]
Print a normal vector of the 0th point
[0. 0. 1.]


To check out other variables, please use help(downpcd). Normal vectors can be transformed as a numpy array using np.asarray.

In [25]:
print("Print the normal vectors of the first 10 points")
print(np.asarray(downpcd_iphone7.normals)[:7, :])
print("Print the normal vectors of the first 10 points")
print(np.asarray(downpcd_kota_circuit2.normals)[:20, :])

Print the normal vectors of the first 10 points
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
Print the normal vectors of the first 10 points
[[ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [-0.70574554  0.70522761 -0.06765539]
 [ 0.          0.          1.        ]
 [ 0.83193173  0.19213863 -0.52055004]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [-0.3815197  -0.71594861 -0.58468821]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [ 0.01626067 -0.36616579 -0.93040755]
 [ 0.81908598  0.48168866  0.31156731]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          1.        ]]


# Crop point cloud

In [ ]:
print("Load a polygon volume and use it to crop the original point cloud")
demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)
chair = vol.crop_point_cloud(pcd)
o3d.visualization.draw_geometries([chair],
                                  zoom=0.7,
                                  front=[0.5439, -0.2333, -0.8060],
                                  lookat=[2.4615, 2.1331, 1.338],
                                  up=[-0.1781, -0.9708, 0.1608])

# Paint point cloud

In [ ]:
print("Paint chair")
chair.paint_uniform_color([1, 0.706, 0])
o3d.visualization.draw_geometries([chair],
                                  zoom=0.7,
                                  front=[0.5439, -0.2333, -0.8060],
                                  lookat=[2.4615, 2.1331, 1.338],
                                  up=[-0.1781, -0.9708, 0.1608])

# Point cloud distance

Open3D provides the method compute_point_cloud_distance to compute the distance from a source point cloud to a target point cloud. I.e., it computes for each point in the source point cloud the distance to the closest point in the target point cloud.

In the example below we use the function to compute the difference between two point clouds. Note that this method could also be used to compute the Chamfer distance between two point clouds.

In [7]:
# Load data
demo_crop_data = o3d.data.DemoCropPointCloud()
pcd = o3d.io.read_point_cloud(demo_crop_data.point_cloud_path)
vol = o3d.visualization.read_selection_polygon_volume(demo_crop_data.cropped_json_path)
chair = vol.crop_point_cloud(pcd_iphone7)

dists = pcd.compute_point_cloud_distance(chair)
dists = np.asarray(dists)
ind = np.where(dists > 0.01)[0]
pcd_without_chair = pcd.select_by_index(ind)
o3d.visualization.draw_geometries([pcd_without_chair],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

[Open3D WARNING] [KDTreeFlann::SetRawData] Failed due to no data.
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] The number of points is 0 when creating axis-aligned bounding box.
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


# Bounding volumes
The PointCloud geometry type has bounding volumes as all other geometry types in Open3D. Currently, Open3D implements an AxisAlignedBoundingBox and an OrientedBoundingBox that can also be used to crop the geometry.

In [ ]:
aabb = chair.get_axis_aligned_bounding_box()
aabb.color = (1, 0, 0)
obb = chair.get_oriented_bounding_box()
obb.color = (0, 1, 0)
o3d.visualization.draw_geometries([chair, aabb, obb],
                                  zoom=0.7,
                                  front=[0.5439, -0.2333, -0.8060],
                                  lookat=[2.4615, 2.1331, 1.338],
                                  up=[-0.1781, -0.9708, 0.1608])

# Convex hull
The convex hull of a point cloud is the smallest convex set that contains all points. Open3D contains the method compute_convex_hull that computes the convex hull of a point cloud. The implementation is based on Qhull.

In the example code below we first sample a point cloud from a mesh and compute the convex hull that is returned as a triangle mesh. Then, we visualize the convex hull as a red LineSet.

In [ ]:
bunny = o3d.data.BunnyMesh()
mesh = o3d.io.read_triangle_mesh(bunny.path)
mesh.compute_vertex_normals()

pcl = mesh.sample_points_poisson_disk(number_of_points=2000)
hull, _ = pcl.compute_convex_hull()
hull_ls = o3d.geometry.LineSet.create_from_triangle_mesh(hull)
hull_ls.paint_uniform_color((1, 0, 0))
o3d.visualization.draw_geometries([pcl, hull_ls])

# DBSCAN clustering
Given a point cloud from e.g. a depth sensor we want to group local point cloud clusters together. For this purpose, we can use clustering algorithms. Open3D implements DBSCAN [Ester1996] that is a density based clustering algorithm. The algorithm is implemented in cluster_dbscan and requires two parameters: eps defines the distance to neighbors in a cluster and min_points defines the minimum number of points required to form a cluster. The function returns labels, where the label -1 indicates noise.

In [ ]:
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud(ply_point_cloud.path)

with o3d.utility.VerbosityContextManager(
        o3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array(
        pcd.cluster_dbscan(eps=0.02, min_points=10, print_progress=True))

max_label = labels.max()
print(f"point cloud has {max_label + 1} clusters")
colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0
pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.455,
                                  front=[-0.4999, -0.1659, -0.8499],
                                  lookat=[2.1813, 2.0619, 2.0999],
                                  up=[0.1204, -0.9852, 0.1215])

# Plane segmentation
Open3D also supports segmententation of geometric primitives from point clouds using RANSAC. To find the plane with the largest support in the point cloud, we can use segment_plane. The method has three arguments: distance_threshold defines the maximum distance a point can have to an estimated plane to be considered an inlier, ransac_n defines the number of points that are randomly sampled to estimate a plane, and num_iterations defines how often a random plane is sampled and verified. The function then returns the plane as (a,b,c,d) such that for each point (x,y,z) on the plane we have ax + by + cz + d = 0. The function further returns a list of indices of the inlier points.

In [ ]:
pcd_point_cloud = o3d.data.PCDPointCloud()
pcd = o3d.io.read_point_cloud(pcd_point_cloud.path)

plane_model, inliers = pcd.segment_plane(distance_threshold=0.01,
                                         ransac_n=3,
                                         num_iterations=1000)
[a, b, c, d] = plane_model
print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")

inlier_cloud = pcd.select_by_index(inliers)
inlier_cloud.paint_uniform_color([1.0, 0, 0])
outlier_cloud = pcd.select_by_index(inliers, invert=True)
o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud],
                                  zoom=0.8,
                                  front=[-0.4999, -0.1659, -0.8499],
                                  lookat=[2.1813, 2.0619, 2.0999],
                                  up=[0.1204, -0.9852, 0.1215])

# Planar patch detection
In addition to finding the single plane with the largest support, Open3D includes an algorithm which uses a robust statistics-based approach for planar patch detection [ArujoAndOliveira2020]. This algorithm first subdivides the point cloud into smaller chunks (using an octree), then attempts to fit a plane to each chunk. If the plane passes a robust planarity test, then it is accepted. A plane is fitted to a subset of points by taking the median point position and the median point normal and estimating a plane . The robust planarity check consists of two main components. First, the distribution of angles between each point normal and the fitted plane normal is found. If the spread of this distribution is too high (i.e., there is too much variance amongst all of the associated point normals), then the plane is rejected. Second, the distribution of the distances from the fitted plane to each point is computed. If the spread of this distribution is too high, as measured using a coplanarity metric (see Fig. 4 of [ArujoAndOliveira2020]), then the plane is rejected. After an initial set of planes are found, an iterative procedure is used to grow and merge planes into a smaller, stable set of planes. These planes can then be bounded using the 2D convex hull of their associated point sets and planar patches are extracted.

To find a list of planar patches in a point cloud, we can use detect_planar_patches. This method can take six arguments: normal_variance_threshold_deg controls the amount of variance allowed amongst the point normals and takes  as its default. Smaller values tends to result in fewer, higher quality planes. coplanarity_deg controls the allowed distribution of point distances from the plane and takes  as its default. Larger values encourage a tighter distribution of points around the fitted plane. outlier_ratio sets the maximum allowable outlier ratio in a fitted planes associated set of points before being rejected and has the default value of 0.75. min_plane_edge_length is used to reject false positives—a planar patch’s largest edge much be greater than this value to be considered a true planar patch. If left at 0, the algorithm defaults to using a value of 1% of the point clouds largest dimension. min_num_points determines how deep the associated octree becomes and how many points must be present when attempting to fit a plane. If left at 0, the algorithm defaults to 0.1% of the number of points in the point cloud. search_param is an instance of geometry::KDTreeSearchParam and defaults to geometry::KDTreeSearchParamKNN. The k nearest neighbors to each point are used when growing and merging planes. Larger values of k tend to produce higher quality patches at the expense of computation. This function then returns a list of detected planar patches, represented as geometry::OrientedBoundingBox objects, with the third column (i.e., ) of R indicating the planar patch normal vector. The extent in the  direction is non-zero so that the OrientedBoundingBox contains the points that contribute to the plane detection. The planar patches can be visualized using the geometry::TriangleMesh::CreateFromOrientedBoundingBox factory function, using the scale parameter to “flatten” the bounding box along the normal, i.e., CreateFromOrientedBoundingBox(obox, scale=[1, 1, 0.0001]).

In [ ]:
dataset = o3d.data.PCDPointCloud()
pcd = o3d.io.read_point_cloud(dataset.path)
assert (pcd.has_normals())

# using all defaults
oboxes = pcd.detect_planar_patches(
    normal_variance_threshold_deg=60,
    coplanarity_deg=75,
    outlier_ratio=0.75,
    min_plane_edge_length=0,
    min_num_points=0,
    search_param=o3d.geometry.KDTreeSearchParamKNN(knn=30))

print("Detected {} patches".format(len(oboxes)))

geometries = []
for obox in oboxes:
    mesh = o3d.geometry.TriangleMesh.create_from_oriented_bounding_box(obox, scale=[1, 1, 0.0001])
    mesh.paint_uniform_color(obox.color)
    geometries.append(mesh)
    geometries.append(obox)
geometries.append(pcd)

o3d.visualization.draw_geometries(geometries,
                                  zoom=0.62,
                                  front=[0.4361, -0.2632, -0.8605],
                                  lookat=[2.4947, 1.7728, 1.5541],
                                  up=[-0.1726, -0.9630, 0.2071])

# Hidden point removal
Imagine you want to render a point cloud from a given view point, but points from the background leak into the foreground because they are not occluded by other points. For this purpose we can apply a hidden point removal algorithm. In Open3D the method by [Katz2007] is implemented that approximates the visibility of a point cloud from a given view without surface reconstruction or normal estimation.

In [ ]:
print("Convert mesh to a point cloud and estimate dimensions")
armadillo = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo.path)
mesh.compute_vertex_normals()

pcd = mesh.sample_points_poisson_disk(5000)
diameter = np.linalg.norm(
    np.asarray(pcd.get_max_bound()) - np.asarray(pcd.get_min_bound()))
o3d.visualization.draw_geometries([pcd])

In [ ]:
print("Define parameters used for hidden_point_removal")
camera = [0, 0, diameter]
radius = diameter * 100

print("Get all points that are visible from given view point")
_, pt_map = pcd.hidden_point_removal(camera, radius)

print("Visualize result")
pcd = pcd.select_by_index(pt_map)
o3d.visualization.draw_geometries([pcd])